name: Test the serving application

on:
  push:
    branches:
      - main
    paths:
      - 'serving/**'
      - 'tests/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'iac/**'

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python3
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: pip3 install -r serving/requirements.txt

    - name: Run Unit Test
      run: pytest